TRACE_META_DIR="./output"
OUTPUT_PATH="./logs_original_image_accuracy/"
LIMIT_ARG="--limit 1000"

python -m run_eval --model qwen2_5_vl --model_args pretrained=Qwen/Qwen2.5-VL-7B-Instruct --tasks vqav2 --batch_size 1 --log_samples --log_samples_suffix llava_vid --output_path $OUTPUT_PATH --write_accuracy $LIMIT_ARG --trace_meta_dir $TRACE_META_DIR
python -m run_eval --model qwen2_5_vl --model_args pretrained=Qwen/Qwen2.5-VL-7B-Instruct --tasks mme --batch_size 1 --log_samples --log_samples_suffix llava_vid --output_path $OUTPUT_PATH --write_accuracy $LIMIT_ARG --trace_meta_dir $TRACE_META_DIR
python -m run_eval --model qwen2_5_vl --model_args pretrained=Qwen/Qwen2.5-VL-7B-Instruct --tasks mmbench --batch_size 1 --log_samples --log_samples_suffix llava_vid --output_path $OUTPUT_PATH --write_accuracy $LIMIT_ARG --trace_meta_dir $TRACE_META_DIR
python -m run_eval --model llava_onevision --model_args pretrained=lmms-lab/llava-onevision-qwen2-7b-ov,conv_template=qwen_1_5,model_name=llava_qwen --tasks vqav2 --batch_size 1 --log_samples --log_samples_suffix llava_onevision --output_path $OUTPUT_PATH --write_accuracy $LIMIT_ARG --trace_meta_dir $TRACE_META_DIR
python -m run_eval --model llava_onevision --model_args pretrained=lmms-lab/llava-onevision-qwen2-7b-ov,conv_template=qwen_1_5,model_name=llava_qwen --tasks mme --batch_size 1 --log_samples --log_samples_suffix llava_onevision --output_path $OUTPUT_PATH --write_accuracy $LIMIT_ARG --trace_meta_dir $TRACE_META_DIR
python -m run_eval --model llava_onevision --model_args pretrained=lmms-lab/llava-onevision-qwen2-7b-ov,conv_template=qwen_1_5,model_name=llava_qwen --tasks mmbench --batch_size 1 --log_samples --log_samples_suffix llava_onevision --output_path $OUTPUT_PATH --write_accuracy $LIMIT_ARG --trace_meta_dir $TRACE_META_DIR